# The key value pairs found below are available within the templates.
# {{site_name}}, {{url}}, {{copyright}} and {{analytics_code}}

:site_name: SYNTOP
:url: http://syntop.io
:copyright: 2012
:piwik_host: analytics.pb.io
:piwik_site_id: 10
